version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_ENV: prod
    volumes:
      - ./logs:/var/log
      - ./public:/srv/app/public:rw

  nginx:
    image: nginx:1.15.3-alpine
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - './docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro'
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email bs@epotato.net --agree-tos --no-eff-email -d mon-bibou.fr -d www.mon-bibou.fr
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot