version: "3.4"

# Test environment override
services:
  php:
    environment:
      APP_ENV: test
    volumes:
      - ./logs:/var/log
      - ./public:/srv/app/public:rw

  nginx:
    image: nginx:1.15.3-alpine
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - './docker/nginx/ssl/live/localhost/localhost.crt:/etc/nginx/ssl/live/localhost/localhost.crt:ro'
      - './docker/nginx/ssl/live/localhost/localhost.key:/etc/nginx/ssl/live/localhost/localhost.key:ro'
      - './docker/nginx/localhost.conf:/etc/nginx/conf.d/default.conf:ro'

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email bs@epotato.net --agree-tos --no-eff-email -d test.mon-bibou.fr
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot