version: "3.4"

# Development environment override
services:
  php:
    volumes:
      - ./:/srv/app:rw,cached
      - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
      - .:/srv/app:rw
    environment:
      APP_ENV: dev
    depends_on:
      - db

  nginx:
    volumes:
      - './docker/nginx/ssl/live/localhost/localhost.crt:/etc/nginx/ssl/live/localhost/localhost.crt:ro'
      - './docker/nginx/ssl/live/localhost/localhost.key:/etc/nginx/ssl/live/localhost/localhost.key:ro'
      - './docker/nginx/localhost.conf:/etc/nginx/conf.d/default.conf:ro'

  db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql:rw
    ports:
      - target: 3306
        published: 3306
        protocol: tcp

volumes:
  db-data: {}
