version: "3.4"

services:
  php:
    build:
      context: .
      target: symfony_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:1.15.3-alpine
    restart: unless-stopped
    depends_on:
        - php
    volumes:
        - '.:/usr/src/app'
    ports:
        - '80:80'
        - '443:443'